### PR TITLE
lib: update libmetal to SHA 695d29ba60a5

### PR DESCRIPTION
**Pull request by carlocaione**
lib: update libmetal to release v2021.10.0

Origin:
        https://github.com/OpenAMP/libmetal

commit:
	695d29ba60a5c4946bb16d2378955fa8bad8bead

Status:
        merge libmetal new version after removing useless dirs and to bring in important fixes and the Xtensa and RISC-V support.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Comment by carlocaione** [comment]
zephyr PR at https://github.com/zephyrproject-rtos/zephyr/pull/43215

**Review by gmarull — APPROVED** [review]

**Comment by arnopo** [comment]
Hi @carlocaione 

As we use to update only on release. Please could you add justification in the commit message to explain why you need this intermediate update?
I suppose that it is for the Zephyr metal_sleep_usec

**Comment by carlocaione** [comment]
> As we use to update only on release. Please could you add justification in the commit message to explain why you need this intermediate update? I suppose that it is for the Zephyr metal_sleep_usec

That and for the Xtensa and RISC-V support.

**Review by tejlmand — APPROVED** [review]
lgtm

**Review by carlescufi — APPROVED** [review]

**Review by arnopo — APPROVED** [review]

**Pull request merged**
