### PR TITLE
lib: update libmetal to release v2022.04.0

### PR DESCRIPTION
**Pull request by carlocaione**
Origin:
        https://github.com/OpenAMP/libmetal

commit:
        2371f615bb0f7968e7bd2483301a9ab9d957bec9

Status:
	merge libmetal new version after removing useless dirs.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Comment by carlocaione** [comment]
No actual changes. Just to align this to the tag.

**Comment by arnopo** [comment]
> No actual changes. Just to align this to the tag.

Could you recheck?  at least you should have this one https://github.com/OpenAMP/libmetal/pull/203
Even if it is only typo fixes.

**Comment by carlocaione** [comment]
@arnopo yup, missed that. Pushed again.

**Comment by arnopo** [comment]
Please, could you add in the commit message a link to the libmetal release?
```
Release Description:
            https://github.com/OpenAMP/libmetal/releases/tag/v2022.04.0    

```
else LGTM

**Comment by carlocaione** [comment]
> Please, could you add in the commit message a link to the libmetal release?

done

**Review by arnopo — APPROVED** [review]

**Pull request merged**
