### PR TITLE
Fixes for building on cortex-A, arm64 and log enhancements

### PR DESCRIPTION
**Pull request by eugenecohen**

### CODE REVIEW

**Comment by galak** [comment]
Have you sent these to upstream libmetal project?

**Comment by eugenecohen** [comment]
> Have you sent these to upstream libmetal project?

No, is that the preferred flow?  I wasn't sure what the rules of the road are for the zephyr modules.

**Comment by galak** [comment]
> No, is that the preferred flow? I wasn't sure what the rules of the road are for the zephyr modules.

It is, we are working on documented standard working procedure for modules.

**Comment by carlocaione** [comment]
What's the status of this PR?

**Comment by quic-egmc** [comment]
superceded by upstream PR https://github.com/OpenAMP/libmetal/pull/208

**Pull request closed without merging**
