### PR TITLE
lib: update libmetal to release v2020.01.0

### PR DESCRIPTION
**Pull request by arnopo**
Origin:
	https://github.com/OpenAMP/libmetal

commit:
	e3dfc2fe85e5ceb8b193c4cf559b17bbd53e8866

Status:
	merge libmetal new version after removing useless dirs.

Release Description:
	https://github.com/OpenAMP/libmetal/releases/tag/v2020.01.0

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@st.com>

### CODE REVIEW

**Comment by arnopo** [comment]
dependency with https://github.com/zephyrproject-rtos/open-amp/pull/4

**Comment by arnopo** [comment]
@ioannisg , @edmooring @karl-zh 
Could you please review and check that does not introduce regression on your platform
Thanks!

**Comment by galak** [comment]
We need a PR on Zephyr that updates west.yml to test this, I'll work that up once I merge https://github.com/zephyrproject-rtos/zephyr/pull/17553

**Comment by galak** [comment]
testing via https://github.com/zephyrproject-rtos/zephyr/pull/23810

**Review by galak — APPROVED** [review]

**Pull request merged**
