### PR TITLE
Update 2020.10.0 

### PR DESCRIPTION
**Pull request by galak**

### CODE REVIEW

**Comment by carlescufi** [comment]
You are using snapshots here right? Not keeping history of the upstream libmetal repo

**Comment by galak** [comment]
zephyr side PR - https://github.com/zephyrproject-rtos/zephyr/pull/29488

**Review by arnopo — APPROVED** [review]
Hi @galak ,
Very proactive :)
The release should be official today. @edmooring will send the official today ( an unexpected mail has been sent yesterday...)
That said the branch is up to date so LGTM

**Comment by galak** [comment]
> You are using snapshots here right? Not keeping history of the upstream libmetal repo

Correct, that's how we've managed the libmetal & openamp modules.

**Review by carlescufi — APPROVED** [review]
Small release I see ;)

Anyway commit looks fine, using snapshot instead of merge

**Comment by arnopo** [comment]
> Hi @galak ,
> Very proactive :)
> The release should be official today. @edmooring will send the official today ( an unexpected mail has been sent yesterday...)
> That said the branch is up to date so LGTM

be careful for the openamp lib, i have updated the release branch this morning

**Pull request merged**
