### PR TITLE
lib: update libmetal to SHA db77c464..

### PR DESCRIPTION
**Pull request by galak**
Origin:
        https://github.com/OpenAMP/libmetal

commit:
        db77c464376e603bc46122b38a7956c87597895b

Status:
        merge libmetal new version after removing useless dirs.

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
Zephyr side PR: https://github.com/zephyrproject-rtos/zephyr/pull/28194

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@galak is this a snapshot? you didn't actually merge right?

**Comment by galak** [comment]
> @galak is this a snapshot? you didn't actually merge right?

Correct, its how we've been doing updates to libmetal to this point.

**Review by tejlmand — APPROVED** [review]

**Review by arnopo — APPROVED** [review]

**Review by arnopo — CHANGES_REQUESTED** [review]
come back to my review...

The commit reference  in https://github.com/zephyrproject-rtos/libmetal/blob/master/README should be updated in consequence

**Comment by galak** [comment]
> come back to my review...
> 
> The commit reference in https://github.com/zephyrproject-rtos/libmetal/blob/master/README should be updated in consequence

Fixed the SHA in the README.

**Review by arnopo — APPROVED** [review]

**Pull request merged**
